Improve error message when Android build is too large (#7395)
* This file doesn't exist anymore

* Catch exception when texture is too large

Building...java.lang.NegativeArraySizeException: -2147483648
	at java.desktop/java.awt.image.DataBufferByte.<init>(DataBufferByte.java:76)
	at java.desktop/java.awt.image.Raster.createInterleavedRaster(Raster.java:310)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:391)
	at com.dynamo.bob.textureset.TextureSetGenerator.composite(TextureSetGenerator.java:481)

* Don't allocate full file size at once

* Updated bundletool from 0.14.0 to 1.14.0

* Update AndroidBundler.java

* Moved file read to helper in FileUtil

* Moved to FileUtil